server:
  port: 9001
  tomcat:
    accept-count: 100
    connection-timeout: 2000
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10
spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/bookshop_catalogdb
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      pool-name: bookshopdb-pool
  jpa:
    hibernate:
      ddl-auto: create-drop