<<<<<<< HEAD
name: CI Pipeline
on: [push]

jobs:
  build:
    name: Run unit and integration tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7
          java-package: jdk
          architecture: x64
      - name: Maven Build (assemble + test)
        run: |
          mvn build
=======
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.7
        java-package: jdk
        architecture: x64
    - name: Build with Maven
      run: mvn -B package --file pom.xml
>>>>>>> origin/master
